# Site wide configuration

title: Andrea G. Cipriani
locale: en_US
description: Personal dev blog
logo: agc.png
search: true
url:
#leave it blank for remote
#http://localhost:4000

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", ".less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]

# Octopress

# Default extensions
post_ext: md
page_ext: md

# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Site owner
owner:
  name: Andrea Cipriani
  avatar: andreacipriani.png
  email: andrea.g.cipriani@gmail.com
  disqus-shortname: AndreaCipriani89
  twitter: andreacipriani
  github: andreacipriani
  stackexchange: http://stackoverflow.com/users/872908/andreacipriani
  #linkedin: #username
  google:
    #plus:
    analytics: UA-78614322-1
    #verify: #verified with html page google826...
    ad-client:
    ad-slot:
    bing-verify:
